// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package db

import (
	"context"
)

const getChangeSeq = `-- name: GetChangeSeq :one
SELECT seq FROM change_counter WHERE id = 1
`

func (q *Queries) GetChangeSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChangeSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const nextChangeSeq = `-- name: NextChangeSeq :one
UPDATE change_counter SET seq = seq + 1 WHERE id = 1
RETURNING seq
`

func (q *Queries) NextChangeSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextChangeSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
