// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec
INSERT INTO folders (id, vault_id, parent_id, name, path, created_at, updated_at, change_seq)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFolderParams struct {
	ID        string
	VaultID   string
	ParentID  *string
	Name      string
	Path      string
	CreatedAt string
	UpdatedAt string
	ChangeSeq int64
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.ExecContext(ctx, createFolder,
		arg.ID,
		arg.VaultID,
		arg.ParentID,
		arg.Name,
		arg.Path,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ChangeSeq,
	)
	return err
}

const getFolderByPath = `-- name: GetFolderByPath :one
SELECT id, vault_id, parent_id, name, path, created_at, updated_at, deleted_at, change_seq FROM folders
WHERE vault_id = ? AND path = ? AND deleted_at IS NULL
`

type GetFolderByPathParams struct {
	VaultID string
	Path    string
}

func (q *Queries) GetFolderByPath(ctx context.Context, arg GetFolderByPathParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByPath, arg.VaultID, arg.Path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChangeSeq,
	)
	return i, err
}
