// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const deleteNoteLinks = `-- name: DeleteNoteLinks :exec
DELETE FROM links WHERE source_note_id = ?
`

func (q *Queries) DeleteNoteLinks(ctx context.Context, sourceNoteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteLinks, sourceNoteID)
	return err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO links (source_note_id, ord, kind, target_raw, heading)
VALUES (?, ?, ?, ?, ?)
`

type InsertLinkParams struct {
	SourceNoteID string
	Ord          int64
	Kind         string
	TargetRaw    string
	Heading      string
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink,
		arg.SourceNoteID,
		arg.Ord,
		arg.Kind,
		arg.TargetRaw,
		arg.Heading,
	)
	return err
}

const listNoteLinks = `-- name: ListNoteLinks :many
SELECT source_note_id, ord, kind, target_raw, heading FROM links
WHERE source_note_id = ?
ORDER BY ord
`

func (q *Queries) ListNoteLinks(ctx context.Context, sourceNoteID string) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listNoteLinks, sourceNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.SourceNoteID,
			&i.Ord,
			&i.Kind,
			&i.TargetRaw,
			&i.Heading,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveNoteName = `-- name: ResolveNoteName :one
SELECT id FROM notes
WHERE vault_id = ?1 AND name COLLATE NOCASE = ?2
  AND trashed_at IS NULL AND deleted_at IS NULL
LIMIT 1
`

type ResolveNoteNameParams struct {
	VaultID string
	Name    string
}

func (q *Queries) ResolveNoteName(ctx context.Context, arg ResolveNoteNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveNoteName, arg.VaultID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}
