// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ChangeCounter struct {
	ID  int64
	Seq int64
}

type Folder struct {
	ID        string
	VaultID   string
	ParentID  *string
	Name      string
	Path      string
	CreatedAt string
	UpdatedAt string
	DeletedAt *string
	ChangeSeq int64
}

type Link struct {
	SourceNoteID string
	Ord          int64
	Kind         string
	TargetRaw    string
	Heading      string
}

type Note struct {
	ID             string
	VaultID        string
	FolderID       string
	Name           string
	Body           string
	Version        int64
	CreatedAt      string
	UpdatedAt      string
	UpdatedByKind  string
	UpdatedByUser  *string
	UpdatedByToken *string
	TrashedAt      *string
	DeletedAt      *string
	ChangeSeq      int64
}

type NoteVersion struct {
	NoteID     string
	Version    int64
	Body       string
	Name       string
	FolderPath string
	SavedAt    string
	ActorKind  string
	ActorUser  *string
	ActorToken *string
}

type ServerConfig struct {
	Key   string
	Value string
}

type Token struct {
	ID         string
	UserID     string
	Kind       string
	Name       string
	TokenHash  string
	Scopes     string
	CreatedAt  string
	LastSeenAt *string
	ExpiresAt  *string
	RevokedAt  *string
}

type User struct {
	ID           string
	Username     string
	Email        *string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    *string
}

type Vault struct {
	ID        string
	OwnerID   *string
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt *string
	ChangeSeq int64
}
