// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (id, vault_id, folder_id, name, body, version, created_at, updated_at, updated_by_kind, updated_by_user, updated_by_token, change_seq)
VALUES (?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?)
`

type CreateNoteParams struct {
	ID             string
	VaultID        string
	FolderID       string
	Name           string
	Body           string
	CreatedAt      string
	UpdatedAt      string
	UpdatedByKind  string
	UpdatedByUser  *string
	UpdatedByToken *string
	ChangeSeq      int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote,
		arg.ID,
		arg.VaultID,
		arg.FolderID,
		arg.Name,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedByKind,
		arg.UpdatedByUser,
		arg.UpdatedByToken,
		arg.ChangeSeq,
	)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, vault_id, folder_id, name, body, version, created_at, updated_at, updated_by_kind, updated_by_user, updated_by_token, trashed_at, deleted_at, change_seq FROM notes
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.FolderID,
		&i.Name,
		&i.Body,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByKind,
		&i.UpdatedByUser,
		&i.UpdatedByToken,
		&i.TrashedAt,
		&i.DeletedAt,
		&i.ChangeSeq,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, vault_id, folder_id, name, version, created_at, updated_at, change_seq
FROM notes
WHERE vault_id = ? AND trashed_at IS NULL AND deleted_at IS NULL
ORDER BY name COLLATE NOCASE
`

type ListNotesRow struct {
	ID        string
	VaultID   string
	FolderID  string
	Name      string
	Version   int64
	CreatedAt string
	UpdatedAt string
	ChangeSeq int64
}

func (q *Queries) ListNotes(ctx context.Context, vaultID string) ([]ListNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, vaultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.FolderID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangeSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesSince = `-- name: ListNotesSince :many
SELECT id, vault_id, folder_id, name, version, created_at, updated_at, change_seq
FROM notes
WHERE vault_id = ? AND change_seq > ? AND trashed_at IS NULL AND deleted_at IS NULL
ORDER BY change_seq
`

type ListNotesSinceParams struct {
	VaultID   string
	ChangeSeq int64
}

type ListNotesSinceRow struct {
	ID        string
	VaultID   string
	FolderID  string
	Name      string
	Version   int64
	CreatedAt string
	UpdatedAt string
	ChangeSeq int64
}

func (q *Queries) ListNotesSince(ctx context.Context, arg ListNotesSinceParams) ([]ListNotesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotesSince, arg.VaultID, arg.ChangeSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesSinceRow
	for rows.Next() {
		var i ListNotesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.FolderID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangeSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotNoteVersion = `-- name: SnapshotNoteVersion :exec
INSERT INTO note_versions (note_id, version, body, name, folder_path, saved_at, actor_kind, actor_user, actor_token)
SELECT n.id, n.version, n.body, n.name, f.path, ?, ?, ?, ?
FROM notes n JOIN folders f ON f.id = n.folder_id
WHERE n.id = ?
`

type SnapshotNoteVersionParams struct {
	SavedAt    string
	ActorKind  string
	ActorUser  *string
	ActorToken *string
	ID         string
}

func (q *Queries) SnapshotNoteVersion(ctx context.Context, arg SnapshotNoteVersionParams) error {
	_, err := q.db.ExecContext(ctx, snapshotNoteVersion,
		arg.SavedAt,
		arg.ActorKind,
		arg.ActorUser,
		arg.ActorToken,
		arg.ID,
	)
	return err
}

const updateNoteBody = `-- name: UpdateNoteBody :execrows
UPDATE notes
SET body = ?, version = version + 1, updated_at = ?, updated_by_kind = ?, updated_by_user = ?, updated_by_token = ?, change_seq = ?
WHERE id = ? AND version = ? AND deleted_at IS NULL
`

type UpdateNoteBodyParams struct {
	Body           string
	UpdatedAt      string
	UpdatedByKind  string
	UpdatedByUser  *string
	UpdatedByToken *string
	ChangeSeq      int64
	ID             string
	Version        int64
}

func (q *Queries) UpdateNoteBody(ctx context.Context, arg UpdateNoteBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNoteBody,
		arg.Body,
		arg.UpdatedAt,
		arg.UpdatedByKind,
		arg.UpdatedByUser,
		arg.UpdatedByToken,
		arg.ChangeSeq,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
