// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (id, user_id, kind, name, token_hash, scopes, created_at, last_seen_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID         string
	UserID     string
	Kind       string
	Name       string
	TokenHash  string
	Scopes     string
	CreatedAt  string
	LastSeenAt *string
	ExpiresAt  *string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, kind, name, token_hash, scopes, created_at, last_seen_at, expires_at, revoked_at FROM tokens
WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserTokens = `-- name: ListUserTokens :many
SELECT id, user_id, kind, name, token_hash, scopes, created_at, last_seen_at, expires_at, revoked_at FROM tokens
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserTokens(ctx context.Context, userID string) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listUserTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens SET revoked_at = ?
WHERE id = ? AND user_id = ? AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt *string
	ID        string
	UserID    string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchToken = `-- name: TouchToken :exec
UPDATE tokens SET last_seen_at = ? WHERE id = ?
`

type TouchTokenParams struct {
	LastSeenAt *string
	ID         string
}

func (q *Queries) TouchToken(ctx context.Context, arg TouchTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchToken, arg.LastSeenAt, arg.ID)
	return err
}
