// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaults.sql

package db

import (
	"context"
)

const createVault = `-- name: CreateVault :exec
INSERT INTO vaults (id, owner_id, name, created_at, updated_at, change_seq)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateVaultParams struct {
	ID        string
	OwnerID   *string
	Name      string
	CreatedAt string
	UpdatedAt string
	ChangeSeq int64
}

func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) error {
	_, err := q.db.ExecContext(ctx, createVault,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ChangeSeq,
	)
	return err
}

const getVault = `-- name: GetVault :one
SELECT id, owner_id, name, created_at, updated_at, deleted_at, change_seq FROM vaults
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetVault(ctx context.Context, id string) (Vault, error) {
	row := q.db.QueryRowContext(ctx, getVault, id)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChangeSeq,
	)
	return i, err
}

const listVaults = `-- name: ListVaults :many
SELECT id, owner_id, name, created_at, updated_at, deleted_at, change_seq FROM vaults
WHERE deleted_at IS NULL
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListVaults(ctx context.Context) ([]Vault, error) {
	rows, err := q.db.QueryContext(ctx, listVaults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vault
	for rows.Next() {
		var i Vault
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChangeSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
